FROM openjdk:8-jre
RUN apt-get update && \
   apt-get install -y wget

RUN echo "Buildtools Container Creatation"
RUN wget http://mirrors.estointernet.in/apache/maven/maven-3/3.6.0/binaries/apache-maven-3.6.0-bin.tar.gz
RUN tar -zxvf apache-maven-3.6.0-bin.tar.gz

ENV PATH /apache-maven-3.6.0/bin

CMD  "mvn" 
